# Generated by Django 6.0.3 on 2026-03-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('pin', '0001_initial'),
        ('save', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55, unique=True)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('gmail', models.CharField(max_length=155, unique=True)),
                ('password', models.CharField(max_length=155)),
                ('data_of_birth', models.DateField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('big_image', models.ImageField(blank=True, null=True, upload_to='background/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save.create')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pin.pin')),
                ('save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save.save')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
